
import React from 'react';
import { useNavigate } from 'react-router-dom';
import AppHeader from '@/components/layout/AppHeader';

const getReductionTier = (pct: number) => {
  if (pct >= 76) return { text: 'text-green-700', label: '⭐ Excellent' };
  if (pct >= 51) return { text: 'text-green-700', label: '✅ Good' };
  if (pct >= 26) return { text: 'text-amber-700', label: '🟡 Moderate' };
  if (pct >= 0) return { text: 'text-red-600', label: '🔴 Mild' };
  return { text: 'text-red-700', label: '⚠️ Increased' };
};

const getArrow = (pct: number) => pct > 0 ? '↓' : pct < 0 ? '↑' : '→';

const Report = () => {
  const navigate = useNavigate();

  const profiles: any[] = (() => { try { return JSON.parse(localStorage.getItem('tens-companion-profiles') || '[]'); } catch { return []; } })();
  const activeId = localStorage.getItem('tens-active-profile-id');
  const profile = profiles.find(p => p.id === activeId) || profiles[0] || null;

  const allAssessments: any[] = (() => { try { return JSON.parse(localStorage.getItem('assessments') || '[]'); } catch { return []; } })();
  const sessions = allAssessments.filter(a => a.type === 'tens-session').sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());

  const validPcts = sessions.filter(s => s.data.reductionPct != null).map(s => s.data.reductionPct as number);
  const avgPct = validPcts.length > 0 ? (validPcts.reduce((a, b) => a + b, 0) / validPcts.length) : 0;

  // Most common tier
  const tierCounts: Record<string, number> = {};
  validPcts.forEach(p => { const t = getReductionTier(p).label; tierCounts[t] = (tierCounts[t] || 0) + 1; });
  const commonTier = Object.entries(tierCounts).sort((a, b) => b[1] - a[1])[0]?.[0] || 'N/A';

  return (
    <div className="min-h-screen flex flex-col">
      <AppHeader />
      <main className="flex-grow">
        <div className="max-w-3xl mx-auto px-6 py-8">
          {/* No-print controls */}
          <div className="no-print flex gap-3 mb-8">
            <button onClick={() => navigate('/dashboard')} className="border border-border rounded-xl px-4 py-2 text-sm hover:bg-medical-50 transition-colors">
              ← Back to Dashboard
            </button>
            <button onClick={() => window.print()} className="bg-medical-600 text-white rounded-xl px-4 py-2 text-sm hover:bg-medical-700 transition-colors">
              🖨️ Print Report
            </button>
          </div>

          {/* Header */}
          <h1 className="text-2xl font-bold text-medical-900">TensPilot+ — TENS Therapy Report</h1>
          <p className="text-sm text-muted-foreground mt-1">Generated: {new Date().toLocaleDateString()}</p>
          <hr className="my-4" />
          <div className="text-xs text-muted-foreground italic border-l-4 border-amber-400 bg-amber-50 px-3 py-2 rounded-r-xl">
            ⚠️ This report is generated by a prototype research device and is not a substitute for professional medical advice.
          </div>

          {/* Patient Summary */}
          {profile && (
            <div className="mt-6">
              <h2 className="font-semibold text-medical-900 mb-2">Patient Summary</h2>
              <div className="text-sm space-y-1">
                <p><span className="text-muted-foreground">Name:</span> {profile.name}</p>
                <p><span className="text-muted-foreground">Primary Condition:</span> {profile.primaryCondition || profile.condition || 'N/A'}</p>
                <p><span className="text-muted-foreground">Medications:</span> {(profile.medications || []).join(', ') || 'None recorded'}</p>
              </div>
            </div>
          )}

          {/* Analytics Summary */}
          <div className="grid grid-cols-3 gap-4 mt-6">
            <div className="border rounded-xl p-4 text-center">
              <p className="text-2xl font-bold text-medical-900">{sessions.length}</p>
              <p className="text-xs text-muted-foreground mt-1">Total Sessions</p>
            </div>
            <div className="border rounded-xl p-4 text-center">
              <p className="text-2xl font-bold text-medical-900">{avgPct.toFixed(1)}%</p>
              <p className="text-xs text-muted-foreground mt-1">Avg Pain Reduction</p>
            </div>
            <div className="border rounded-xl p-4 text-center">
              <p className="text-2xl font-bold text-medical-900">{commonTier}</p>
              <p className="text-xs text-muted-foreground mt-1">Avg Relief</p>
            </div>
          </div>

          {/* Session History Table */}
          {sessions.length > 0 && (
            <div className="mt-6 overflow-x-auto">
              <table className="w-full text-sm border-collapse">
                <thead>
                  <tr className="bg-medical-50 font-semibold text-medical-900">
                    <th className="text-left p-2">Date</th>
                    <th className="text-left p-2">Location</th>
                    <th className="text-left p-2">Type</th>
                    <th className="text-left p-2">Freq</th>
                    <th className="text-center p-2">Before</th>
                    <th className="text-center p-2">After</th>
                    <th className="text-center p-2">Relief%</th>
                    <th className="text-left p-2">Notes</th>
                  </tr>
                </thead>
                <tbody>
                  {sessions.map((s, i) => {
                    const rPct = s.data.reductionPct;
                    const tier = rPct != null ? getReductionTier(rPct) : null;
                    return (
                      <tr key={i} className={i % 2 === 0 ? 'bg-white' : 'bg-gray-50'}>
                        <td className="p-2">{new Date(s.timestamp).toLocaleDateString()}</td>
                        <td className="p-2 capitalize">{s.data.placement?.replace('-', ' ')}</td>
                        <td className="p-2">{s.data.painTypeMode === 'acute' ? '🦴 Acute' : s.data.painTypeMode === 'chronic' ? '⚡ Chronic' : '—'}</td>
                        <td className="p-2">{s.data.frequency}</td>
                        <td className="p-2 text-center">{s.data.painBefore}</td>
                        <td className="p-2 text-center">{s.data.painAfter}</td>
                        <td className={`p-2 text-center font-medium ${tier?.text || ''}`}>
                          {rPct != null ? `${getArrow(rPct)}${rPct}%` : '—'}
                        </td>
                        <td className="p-2 text-xs">{s.data.notes || '—'}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default Report;
